### PR TITLE
Avoid invalid search query when no mon or osd roles are found

### PR DESCRIPTION
**Pull request by rhafer**
Note this is an (almost) blind fix. Not sure if this is correct. But endless while loop in ```mon_secret``` should surely be addressed.

### CODE REVIEW

**Comment by jsuchome** [comment]
I guess you wanted to have ***Do not loop*** in the commit message.

That ``return []`` should probably be good in get_osd_nodes as well (also the empty else branch).

In general, this makes sense, I wonder why was the loop even there...

**Comment by tboerger** [comment]
LGTM

**Comment by rhafer** [comment]
> I guess you wanted to have Do not loop in the commit message.

True :). Fixed that.

> That return [] should probably be good in get_osd_nodes as well

Yeah, right. Added it there as well.

**Comment by jsuchome** [comment]
+1

**Comment by mjura** [comment]
Looks cool!
:+1:

**Comment by vuntz** [comment]
So what happens when `mon_secret` returns `nil`? Do the recipes handle that well?

**Comment by rhafer** [comment]
Hm, actually with  https://github.com/crowbar/barclamp-ceph/pull/138 merged ```mon_secret``` doesn't seem to be used anywhere anymore. We can just remove that I guess :)

**Comment by vuntz** [comment]
@rhafer: agreed, let's drop it!

**Comment by vuntz** [comment]
`mon_secret` dropped in https://github.com/crowbar/barclamp-ceph/pull/147. I still think this PR has some useful bits (first commit), so not closing.

**Comment by rhafer** [comment]
Rebased and dropped no longer needed ```mon_secret``` related commit.

**Comment by vuntz** [comment]
+1

**Pull request merged**
