### PR TITLE
Remove unneeded recipes for glance and cinder integration

### PR DESCRIPTION
**Pull request by mjura**
Depends on:

- https://github.com/crowbar/barclamp-glance/pull/259
- https://github.com/crowbar/barclamp-cinder/pull/243

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by jsuchome** [comment]
+1

**Comment by rhafer** [comment]
@mjura Please rebase

**Comment by rhafer** [comment]
The corresponding PR for cinder and glance have been merged. So this can be merged now as well.

**Pull request merged**
