### PR TITLE
Skip SLE11 nodes in default proposal

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by tboerger** [comment]
I would prefer an implementation based on the constraints.

**Comment by dirkmueller** [comment]
@tboerger can you suggest an implementation ?

**Comment by tboerger** [comment]
Not directly out of the head, but after merging Albertos pull request you can get a generic list of the platform constraints with something like this:

```ruby
role_constraints.values.map do |v|
  v["platform"] || nil
end.uniq
```

This mixes all role constraints together, so this is not really good yet. Maybe it have to be moved down and have to be put into a helper method that can be reused on various places.

**Comment by dirkmueller** [comment]
@tboerger agreed, I have no problem with switching to a "get_default_nodes(rolename/constraint)" helper that returns all nodes that match the constraints once it becomes available.

**Comment by tboerger** [comment]
But if this is not tracked anywhere this will ne er happen...

**Comment by dirkmueller** [comment]
@tboerger created https://trello.com/c/8nvjEfxY and https://trello.com/c/0yYXOdK0 for this.

**Comment by tboerger** [comment]
:+1:

**Comment by vuntz** [comment]
@dirkmueller @tboerger I just wrote https://github.com/crowbar/barclamp-ceph/pull/116 quickly (without having read your latest comments). Doesn't deal with clusters, though.

**Comment by dirkmueller** [comment]
@vuntz: thanks. I appreciate code over trello cards any time ;-) closing.

**Pull request closed without merging**
